arch: amd64
os: linux
dist: focal

notifications:
  email: false
  slack:
    secure: ilztqDylzgDwnh+AAHdrmHjgD4rjutJa5rh783H8HfW7KKY+RtHaAa+Z9V6uAbU3/fPk29fkCXRxT/scAI4Fn0TQ/Hi0alCs7ytNJg+2fbVcI5xWHbmJznOb0pQl0Gn6MGwouSyP9WvRtivtT5u+wlNR6yKycTmUI9qP3Fe7nA/k/WdRt5SHGjjprtYZYbBOg+9UStzubMuQj5hTBeDs78UyUbejSsZ0Cp9+OkTcugoEegwn0o9QdkvFGHF/hQ5bVGGNVAFUVOg+B4DFiw59MbsgIDZ663CXCTxUJ1I4uS3rI7LpnY2G8c5dKp9E2KDkM8sPKWzg4qeyj1POMPNDUbNYWIHBBK4NxrQ+PqW1nquxNTVsqYi2IXVmV2BWx9+SUS06YwDsjrCcQyAtnCzxn/tL3aX/8jyeN3yPwytJgDuj9IF8nIJZuuMgDOs1ZVa9fbL8ANBMcZMKIPCSwjO8670ULl5xKAWKGTY7HwzGLU3syQBwOX+eukf9zx2Y9qrsP1kJJT8YTOD45icJRAMPQQEiN20wxKh/V7Kz0ewc6LG8Bv1FyM6f+7ehNZvkwrStzJJ85JwDkPeTKKiBa3kuBQzE0CBm3/cTYCXgQEo3jggH1xPF8OkbYhuX8TrZjp3PBVCABto6V6OGILFA7Hhv6gK9eHxCSVOICPfWCfYXakY=

language: cpp

# Don't shallow clone as this may break the versioning
git:
  depth: false

branches:
  only:
  - master
  - development
  - /^v?((\d+)(\.\d+)*)(-?(a|b|c|rc|alpha|beta)([0-9]+)?)?$/

# BUILD MATRIX
jobs:
  fast_finish: true
  include:

  - stage: test
    os: windows
    before_install:
        - choco install python3 --version 3.5.4 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip

  - stage: test
    os: windows
    before_install:
        - choco install python3 --version 3.7.4 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip

  - stage: test
    os: osx
    osx_image: xcode11.6
    before_install:
      - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
      - chmod +x miniconda.sh
      - ./miniconda.sh -b
      - export PATH=/Users/travis/miniconda3/bin:$PATH
      - conda update --yes conda
      - conda create --yes -n env_name python=3.5.3 pip numpy
      - source activate env_name
      
  - stage: test 
    os: osx
    osx_image: xcode12.2
    before_install:
      - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
      - chmod +x miniconda.sh
      - ./miniconda.sh -b
      - export PATH=/Users/travis/miniconda3/bin:$PATH
      - conda update --yes conda
      - conda create --yes -n env_name python=3.7.4 pip numpy
      - source activate env_name

  - stage: test 
    os: linux
    dist: bionic
    compiler: gcc
    python: 3.5

  - stage: test
    os: linux
    dist: focal
    compiler: gcc
    python: 3.7

before_install:
  - uname -a
  - $CXX --version
  - cmake --version

install:
  - mkdir -p build && cd build;
  - |
      if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        cmake -DCMAKE_BUILD_TYPE=RELEASE -DGETEIGEN=ON -DGETPYBIND11=ON -DGAMER_TESTS=on -DBUILD_PYGAMER=on -G "Visual Studio 15 2017 Win64" ..
      else
        cmake -DCMAKE_BUILD_TYPE=RELEASE -DGETEIGEN=ON -DGETPYBIND11=ON -DGAMER_TESTS=on -DBUILD_PYGAMER=on ..
      fi
  - cmake --build . --config Release

script:
  - ctest -C Release -V -j
